### ISSUE TITLE
A Minor Drawback

### ISSUE THREAD

**Issue by jmp0xf** [st4lk/django-solid-i18n-urls#10]
If ```SOLID_I18N_USE_REDIRECTS``` is set to be ```True```, the url containing default language code would be unable to route, which is not a friendly behaviour in my opinion.

**Comment by st4lk** [comment]
Hi, thanks for reporting!
What do you mean by "unable to route"? It is about the case, when client have language other than default language of web application and he'll get redirect 301 or 302?
But exactly this behaviour you get, if `SOLID_I18N_USE_REDIRECTS = True`.
By the way, default django i18n process will always return 301 or 302 redirect if you request url without language code.

**Comment by jmp0xf** [comment]
eg. The default language code is "en". Trying to access "http://example.com/en" will get a 404 response.

**Comment by st4lk** [comment]
Ah, agree, that make sense

**Comment by st4lk** [comment]
One note: If prefix with default language code is present in url, exactly that language will be rendered, redirect will not occur.
Uploaded version v0.6.1

**Comment by st4lk** [comment]
@jmp0xf i've added some settings to control default language prefix behaviour #12 .
Probably you'll be interested in [`SOLID_I18N_DEFAULT_PREFIX_REDIRECT = True`](https://github.com/st4lk/django-solid-i18n-urls#settings).
This setting is available in v0.7.1 from pypi.

**Comment by jmp0xf** [comment]
it seems that it cannot work properly with ```SOLID_I18N_USE_REDIRECTS = True```

**Comment by st4lk** [comment]
Precise, what behaviour do you expect and what you get?

**Comment by jmp0xf** [comment]
it does show the page with proper language when ```SOLID_I18N_DEFAULT_PREFIX_REDIRECT = True```. However the language setting will not be changed.
if both ```SOLID_I18N_USE_REDIRECTS``` and ```SOLID_I18N_DEFAULT_PREFIX_REDIRECT``` are set to be True, visiting url with default language prefix will redirect to url with current language prefix.

**Comment by st4lk** [comment]
You mean, when
```
LANGUAGE_CODE = 'en'  # default language
LANGUAGES = (('ru', 'Russian'), ('en', 'English'))
```
url `/en/...` must render english content in every case, even if preferred language is Russian?
In that case you should not use `SOLID_I18N_DEFAULT_PREFIX_REDIRECT = True`, use `SOLID_I18N_DEFAULT_PREFIX_REDIRECT = True` instead.

**Comment by jmp0xf** [comment]
However, changing preferred language in terms of language prefix in url is the behaviour for non-default language prefix.

**Comment by st4lk** [comment]
Preferred language is never changed implicitly. If i understand you correctly, you mean that by accessing url with non-default language prefix, i.e. `/ru/...`, we somehow change user's preferred language. But it is not. Language prefix just have higher priority over user's preferences in discovering language for current request.
By default in django (without solid-i18n), when you access `/ru/` url you'll always get Russian content. Even if your preferred language is English. But url `/` will redirect you to `/en/`.

solid-i18n follows this strategy, except when both settings `SOLID_I18N_DEFAULT_PREFIX_REDIRECT` and `SOLID_I18N_USE_REDIRECTS` are set to `True`. In that case you can't see English content just by visiting `/en/` url. You need to set your preferred language explicitly first (by sending POST to [set_language](https://docs.djangoproject.com/en/dev/topics/i18n/translation/#the-set-language-redirect-view) view).

**Comment by jmp0xf** [comment]
My fault, it url with language prefix does not change the language setting and yes, it should not do that. The actual problem lies in reversing named URLs in my observation. With  ```SOLID_I18N_HANDLE_DEFAULT_PREFIX = True```, the named url cannot be parsed to contain corresponding language prefix in rendered page with default language prefix in url. However, a non-default language prefixed page can handle it properly.

**Comment by jmp0xf** [comment]
```python
if language_code != settings.LANGUAGE_CODE:
-                regex_compiled = re.compile('^%s/' % language_code, re.UNICODE)		+                regex = '^%s/' % language_code
+            elif getattr(settings, 'SOLID_I18N_HANDLE_DEFAULT_PREFIX', False):
+                regex = '(?:^%s/)?' % language_code
             else:		             else:
-                regex_compiled = re.compile('(?:^%s/)?' % language_code, re.UNICODE)		+                regex = ''
```

**Comment by jmp0xf** [comment]
```python
if language_code != settings.LANGUAGE_CODE:
                regex = '^%s/' % language_code
            elif getattr(settings, 'SOLID_I18N_HANDLE_DEFAULT_PREFIX', False):
                regex = '(?:^%s/)?' % language_code
            else:
                regex = ''
```

**Comment by st4lk** [comment]
```
LANGUAGE_CODE = 'en'
LANGUAGES = (('ru', 'Russian'), ('en', 'English'))

urlpatterns = solid_i18n_patterns('',
    url(r'^$', home_view, name='home'),
    url(r'^about/$', about_view, name='about'),
)
```
##### `SOLID_I18N_HANDLE_DEFAULT_PREFIX = False`

        with translation.override('en'):
            url = reverse('about')  # /about/
        with translation.override('ru'):
            url = reverse('about')  # /ru/about/

##### `SOLID_I18N_HANDLE_DEFAULT_PREFIX = True`

        with translation.override('en'):
            url = reverse('about')  # /about/
        with translation.override('ru'):
            url = reverse('about')  # /ru/about/

What you need instead of this?

**Comment by st4lk** [comment]
By the way, this code:
```
if language_code != settings.LANGUAGE_CODE:
                regex = '^%s/' % language_code
            elif getattr(settings, 'SOLID_I18N_HANDLE_DEFAULT_PREFIX', False):
                regex = '^%s/' % language_code
            else:
                regex = ''
```
will respond 404 for root urls (without language prefix), if `SOLID_I18N_HANDLE_DEFAULT_PREFIX = True`.

**Comment by jmp0xf** [comment]
I think I was trying to say "when we request url with default language prefix, reverse all other urls with default language prefix"
