### ISSUE TITLE
Default language problem

### ISSUE THREAD

**Issue by alvaro-rm** [st4lk/django-solid-i18n-urls#11]
Being 'en-us' the default language_code, when I try to open www.myweb.com/myView with a language code 'en-us' it opens the 'en-us' version. That makes sense.
But when I try to open www.myweb.com/writeWhatYouWant/myView with a language code of 'en-us' it also opens the 'en-us' version and I do not understand why. The only possible URL for an "en-us" language code should be without any preffix so -->> www.myweb.com/myView  If anyone opens www.myweb.com/XXXXXX/myView they should get a 404 saying that the urls do not match with any url in urls.py

Is that a bug? Am I doing anything wrong?

**Comment by st4lk** [comment]
Hi, alvaro-rm!
Precise, what version of solid-i18n are you using? Is it v0.6.1?
In this version #10 issue is implemented: default language (english in your case) can be accessed both by `/` and `/en/` urls. But only by these urls, not `/writeWhatYouWant/`.
Check [example project](https://github.com/st4lk/django-solid-i18n-urls#example-site), page http://127.0.0.1:8000/writeWhatYouWant/about/ respond 404.

**Comment by st4lk** [comment]
@alvaro-rm , can you please tell, are you still facing with some unexpected behaviour in current version of solid_i18n (v0.9.1) ?

**Comment by st4lk** [comment]
closing this issue, not enough information
