### ISSUE TITLE
SOLID_I18N_HANDLE_DEFAULT_PREFIX behaviour

### ISSUE THREAD

**Issue by st4lk** [st4lk/django-solid-i18n-urls#14]
When `SOLID_I18N_HANDLE_DEFAULT_PREFIX = True` and default language prefix is present in url, all other urls must be reversed also with that prefix (using [reverse()](https://docs.djangoproject.com/en/dev/ref/urlresolvers/#reverse) or [{% url 'name' %}](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#url)). And if prefix is not in url - reverse without it.
Currently in case of default language all urls are always reversed without language prefix.
Related conversation is in comments of issue  #10

**Comment by st4lk** [comment]
@jmp0xf check current version from pypi ([v0.8.1](https://pypi.python.org/pypi/solid_i18n/0.8.1)). I think now behaviour is correct with `SOLID_I18N_HANDLE_DEFAULT_PREFIX = True`

**Comment by jmp0xf** [comment]
With setting ```SOLID_I18N_USE_REDIRECTS = True``` and ```SOLID_I18N_HANDLE_DEFAULT_PREFIX = True```, the url name resolver seems OK now.  But the new problem I encountered is that after the language is set to default, the url with no language code prefix cannot be resolved.

**Comment by st4lk** [comment]
@jmp0xf can you please open a new issue with detailed description of problem, because currently in [example project](https://github.com/st4lk/django-solid-i18n-urls/tree/master/example) i don't see any problems.

**Comment by jmp0xf** [comment]
That would be weird, I just tested the example with setting ```SOLID_I18N_USE_REDIRECTS = True``` and ```SOLID_I18N_HANDLE_DEFAULT_PREFIX = True``` in Django 1.7.5, resulting in the same problem.
