### ISSUE TITLE
 please release SOLID_I18N to support Django 1.8

### ISSUE THREAD

**Issue by museghost** [st4lk/django-solid-i18n-urls#19]
At first, thank you for your effort ! This is what I want to find out. BTW could you please release SOLID_I18N to support Django 1.8 as well ?? If you do that, I really thank you again.

**Comment by st4lk** [comment]
Hi!
I'll work on this issue in next couple of days.

**Comment by st4lk** [comment]
Linked issue: #8

**Comment by st4lk** [comment]
Now support django 1.8, uploaded to pypi version [v1.0.0](https://pypi.python.org/pypi/solid_i18n).
Thanks for keeping package up to date!
