### ISSUE TITLE
`resolve()` doesn't work

### ISSUE THREAD

**Issue by rory** [st4lk/django-solid-i18n-urls#28]
I have enabled this on a Django 1.6 site. I am trying to use [this snippet](http://stackoverflow.com/a/17351858/161922) which calls `resolve()` on a url (to get the view), and it's not matching anything, and throwing a 404 exception. `en` is my default language, and I have `fr` and `de` enabled.

From stepping into the code, it looks like in the [`resolve` method](https://github.com/django/django/blob/37ea3cb03e80de80380009a7a7939bc48d75abe9/django/core/urlresolvers.py#L333), it's calling `self.regex`, which IME will be `^en/`. Even though `/` works.

Is there any way to get use solid-i18n-urls and have something like `resolve('/')` work? Or have I missed something?

**Comment by st4lk** [comment]
Hi Rory, thanks for reporting.
I see same behaviour with django's builtin [i18n_patterns](https://docs.djangoproject.com/en/dev/topics/i18n/translation/#django.conf.urls.i18n.i18n_patterns), looks like it is not the case of solid_i18n_patterns.

**Comment by st4lk** [comment]
Closing, as it is django's default behaviour
