### ISSUE TITLE
Redirect from URL without any prefix

### ISSUE THREAD

**Issue by graup** [st4lk/django-solid-i18n-urls#30]
Want I want to achieve is this:

/ --> Redirect to user's language (session or cookie), e.g. /en/
/en/ --> Display content in en
/de/ --> Display content in de

If user has no language set, use default language.

Is that possible with this module?

**Comment by st4lk** [comment]
Looks like you described default behaviour of django.

**Comment by st4lk** [comment]
So what for do you need external module?

**Comment by graup** [comment]
Oh, I see. Thank you :)
