### ISSUE TITLE
TemplateDoesNotExist at /fr/

### ISSUE THREAD

**Issue by amehdi92** [st4lk/django-solid-i18n-urls#31]
Hello,

I'm working on a bilingual website and decided to use django-solid-i18n. However, after putting my index in /static/templates/fr and /static/templates/en, I got the message: TemplateDoesNotExist at /fr/.

Here's my views.py:

from django.shortcuts import render

def home(request):
	context={}
	template='index.html'
	return render(request,template,context)
	

And urls.py:
from django.contrib import admin
from django.conf.urls import patterns, include, url
from solid_i18n.urls import solid_i18n_patterns
import profiles.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns = solid_i18n_patterns('',
   url(r'^$', profiles.views.home, name='home'),

    
)

**Comment by st4lk** [comment]
Hello!
This is not the way how translation works in django. You don't need to have separate template for each language. Create one template, mark translatable strings (for example by using [`{% trans '...' %}`](https://docs.djangoproject.com/en/dev/topics/i18n/translation/#trans-template-tag) template tag) and translate those strings. Please, read the [docs](https://docs.djangoproject.com/en/dev/topics/i18n/translation/) carefully.

**Comment by st4lk** [comment]
Closing, if some additional help is needed, please reopen
