### ISSUE TITLE
Deprecation of prefix argument.

### ISSUE THREAD

**Issue by julianwachholz** [st4lk/django-solid-i18n-urls#8]
The `prefix` argument to pattern() functions will be deprecated, see https://docs.djangoproject.com/en/dev/ref/urls/#django.conf.urls.patterns for info.

Since i18n_patterns rely on more than just the prefix, the argument should be made optional.
E.g. if first argument is a URL instance just add it to the list and carry on.

**Comment by alvaro-rm** [comment]
Being 'en-us' the default language_code, when I try to open www.myweb.com/myView with a language code 'en-us'  it opens the 'en-us' version. That makes sense.
But when I try to open www.myweb.com/writeWhatYouWant/myView with a language code of 'en-us' it also opens it and I do not understand why. The only possible URL for an "en-us" language code should be without any preffix so -->> www.myweb.com/myView

Is that a bug? Am I doing anything wrong?

**Comment by st4lk** [comment]
Merged, now in [v1.0.0](https://pypi.python.org/pypi/solid_i18n).
Thanks for contributing!
